export enum ServiceName {
  AUTH_SERVICE = "AUTH_SERVICE",
  USER_SERVICE = "USER_SERVICE",
  EVENT_SERVICE = "EVENT_SERVICE",
  TICKET_SERVICE = "TICKET_SERVICE",
  PAYMENT_SERVICE = "PAYMENT_SERVICE",
  NOTIFICATION_SERVICE = "NOTIFICATION_SERVICE",
  LOGGER_SERVICE = "LOGGER_SERVICE",
}
